### ISSUE TITLE
Function features not working after install 

### ISSUE THREAD

**Issue by bigdoods** [bonanitech/midnight-red#18] opened 2019-06-07 09:44 UTC
Nice work but, I have found the following issues which are notable in my productivity whilst working in function edit. I would expect all of the following to behave as per normal node-red.

1. CTRL+/ does not comment lines. 
2. CTRL+" does not add double quotes to highlighted strings.
3. When there is a syntax error, there is no longer highlighting/underlining of the problem.

Also, I find that highlighting words in grey with white text is not so nice on the eye and really difficult to read. 

Finally, thank you for this theme - It makes it so much easier on my eyes working in node-red for long times!

nr - v.0.20.0

**Comment by bonanitech** [comment] 2019-06-07 12:41
> CTRL+/ does not comment lines.
> CTRL+" does not add double quotes to highlighted strings.
> When there is a syntax error, there is no longer highlighting/underlining of the problem.

Again, those are issues related to Node-RED, not to the theme itself. Please use the [forum](https://discourse.nodered.org/) for those questions.

> Also, I find that highlighting words in grey with white text is not so nice on the eye and really difficult to read.

Could you provide screenshots so we can identify where exactly the problem is?

> Finally, thank you for this theme - It makes it so much easier on my eyes working in node-red for long times!

😃

**Comment by bonanitech** [comment] 2019-06-15 01:20
Closing this issue since we had no feedback for more than a week.

Please raise a new issue if needed.

**Closed by bonanitech** 2019-06-15 01:20 UTC
